### ISSUE TITLE
node_template/hpc.nodes.Compute: add attributes 

### ISSUE THREAD

**Issue by Trophime** [MSO4SC/cloudify-hpc-plugin#51] opened 2018-06-04 07:11 UTC
Hi,
Following TOSCA Simple profile YAML Version 1.0 specs,
it seems to be feasible to define attributes see 16.3 ex.

The idea here would be to retrieve from the hpc definition, the list of partitions defined in this hpc for instance with sinfo or scontrol. Of course, we also need a mechanism to set the prefered partition.

Pushing this idea one step further, it would be possible to have the limits characteristics for each partition, thus providing bounds for other fields like max_time or parallel_tasks...

Same should be doable for reservation, I guess.

This would greatly simplify the def and use of hpc in blueprint for the famous "one click" target

**Comment by emepetres** [comment] 2018-06-04 11:35
Duplicate of #15

**Closed by emepetres** 2018-06-04 11:35 UTC
Labels: duplicate
